name: FedZK CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e .
        
    - name: Run tests
      run: |
        pytest -v
        
    - name: Test client functionality
      run: |
        mkdir -p client_output
        python -m fedzk client train
        python -m fedzk client prove
        
    - name: Test benchmark CLI help
      run: |
        python -m fedzk benchmark run --help

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: client-output
        path: client_output/
        retention-days: 1