name: FedZK CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        
    - name: Run tests with coverage
      run: |
        pytest -v --cov=fedzk --cov-report=xml
        
    - name: Test client functionality
      run: |
        mkdir -p client_output
        python -m fedzk client train || true
        python -m fedzk client prove || true
        
    - name: Test benchmark CLI help
      run: |
        python -m fedzk benchmark run --help || true

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: client-output
        path: client_output/
        retention-days: 1