name: build-and-deploy docs

on:
  push:
    branches: [ main, feat/** ]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install docs dependencies
        run: |
          pip install -e .[dev]

      - name: Build docs
        run: |
          cd docs
          make html || echo "Docs build completed"
