name: build-and-deploy docs

on:
  push:
    branches: [ main, feat/** ]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    continue-on-error: true     # don't fail PR on docs build yet
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs deps
        run: |
          pip install "mkdocs-material" pymdown-extensions mdx_include mkdocs-gen-files

      - name: Build docs
        run: mkdocs build --config-file fedzk/scripts/ci/mkdocs.yml
